// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgg42nD6i02c1ci2eVAV88n2LDYMw9W8',
    appId: '1:1057529410275:web:7fb748ad884f023edccbd6',
    messagingSenderId: '1057529410275',
    projectId: 'news-fire-d721c',
    authDomain: 'news-fire-d721c.firebaseapp.com',
    storageBucket: 'news-fire-d721c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnKYeivP04IEdnYKuB8ZVpAw7nfOSena8',
    appId: '1:1057529410275:android:3ab8a3c3575e5ff3dccbd6',
    messagingSenderId: '1057529410275',
    projectId: 'news-fire-d721c',
    storageBucket: 'news-fire-d721c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2M1lT-5ZEt29isQpe-MKkThtJHNNfXcc',
    appId: '1:1057529410275:ios:f7a6b261a036776bdccbd6',
    messagingSenderId: '1057529410275',
    projectId: 'news-fire-d721c',
    storageBucket: 'news-fire-d721c.appspot.com',
    iosBundleId: 'com.example.newsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2M1lT-5ZEt29isQpe-MKkThtJHNNfXcc',
    appId: '1:1057529410275:ios:f7a6b261a036776bdccbd6',
    messagingSenderId: '1057529410275',
    projectId: 'news-fire-d721c',
    storageBucket: 'news-fire-d721c.appspot.com',
    iosBundleId: 'com.example.newsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgg42nD6i02c1ci2eVAV88n2LDYMw9W8',
    appId: '1:1057529410275:web:96294d775e7357b7dccbd6',
    messagingSenderId: '1057529410275',
    projectId: 'news-fire-d721c',
    authDomain: 'news-fire-d721c.firebaseapp.com',
    storageBucket: 'news-fire-d721c.appspot.com',
  );
}
